# Generated by Django 5.2 on 2025-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('rue', models.CharField(blank=True, max_length=255, null=True)),
                ('gouvernorat', models.CharField(blank=True, max_length=100, null=True)),
                ('delegation', models.CharField(blank=True, max_length=100, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('gouvernorat', models.CharField(max_length=100)),
                ('delegation', models.CharField(max_length=100)),
                ('localite', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('gsm', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
