# Generated by Django 5.2 on 2025-05-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_password_alter_client_gouvernorat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_contrat', models.CharField(max_length=50, unique=True)),
                ('numero_contrat', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=50)),
                ('code_cf', models.CharField(max_length=50)),
                ('ref_offre', models.CharField(max_length=100)),
                ('statut_commercial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_facture', models.CharField(max_length=50, unique=True)),
                ('code_compte_facturation', models.CharField(max_length=50)),
                ('numero_facture', models.CharField(max_length=50)),
                ('montant_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reste_a_payer', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('echeance', models.DateField()),
                ('prise_en_charge', models.BooleanField(default=False)),
                ('date_prise_en_charge', models.DateField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.contrat')),
            ],
        ),
    ]
