# Generated by Django 5.2 on 2025-07-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_alter_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_contrat', models.CharField(max_length=100, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('statut_commercial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_facture', models.CharField(max_length=100, unique=True)),
                ('numero_facture', models.CharField(max_length=100)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_fin', models.DateField()),
                ('contrats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.contrats')),
            ],
        ),
    ]
