# Generated by Django 5.2 on 2025-09-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscription_facturee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('client', 'contrat')},
        ),
    ]
