# Generated by Django 5.2 on 2025-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrats',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
