# Generated by Django 5.2 on 2025-09-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturee',
            old_name='date_generation',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='facturee',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.subscription'),
        ),
    ]
