# Generated by Django 5.2 on 2025-09-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reclam_delete_reclamation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reclam',
            new_name='Reclamation',
        ),
    ]
