# Generated by Django 5.2 on 2025-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_reclam_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
