"""
Django settings for topnet_client project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9bc%c2##ar2)g9wfw)54w6t4)xtpsyhz@h!z$41=uw@8xnzrv3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
'rest_framework_simplejwt.token_blacklist',
    # Your app
    'core',
'corsheaders',
    # 3rd-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'channels',
    'video',
    'django_prometheus'
]
ASGI_APPLICATION = 'topnet_client.asgi.application'
# settings.py


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '172.17.0.1',  # Docker bridge network IP
    '*',  # Only use in development
]
MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',

]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.CustomJWTAuthentication",  # for clients
        "core.authentication.AdminJWTAuthentication",   # for admins
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


SIMPLE_JWT = {
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_CLAIM": "user_id",   # ✅ ici user_id
    "USER_ID_FIELD": "id",        # ✅ reste id
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
}





ROOT_URLCONF = 'topnet_client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'topnet_client.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'topnet_db',
        'USER': 'postgres',
        'PASSWORD': '1995',
        'HOST': 'db',
        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True


import os 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Flouci API credentials
FLOUCI_APP_PUBLIC = "your_app_public"
FLOUCI_APP_SECRET = "your_app_secret"
FLOUCI_API_KEY = "your_api_key"  # sometimes required for payment
FLOUCI_BASE_URL = "https://developers.flouci.com/partners"
FLOUCI_PAYMENT_BASE_URL = "https://api.konnect.network/api/v1"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "tareksoualhia.2016@gmail.com"   # your Gmail
EMAIL_HOST_PASSWORD = "ycxzodcfjjrpahxy"          # your App Password (without spaces)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# reCAPTCHA keys

# reCAPTCHA configuration
RECAPTCHA_SITE_KEY = "6LcwtMwrAAAAAFw8H_aK2p9d-ei-ZGQ4tEHau_k-"   # Public, used in Angular
RECAPTCHA_SECRET_KEY = "6LcwtMwrAAAAF5TaDPG14oFM7X8UO-kiEs_vPsc"   # Secret, used only in Django

HCAPTCHA_SECRET_KEY = "e9e85414-4620-4cb8-a598-92e4877ccf96"


AUTHENTICATION_BACKENDS = [
    'core.authentication.AdminAuthBackend',
    'core.authentication.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# settings.py
import os
from dotenv import load_dotenv

load_dotenv()  # ✅ Loads variables from .env file

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")



STRIPE_PUBLISHABLE_KEY = "pk_test_51S8eQe8tFl7QNgQUU8EtXxnUJF0AmkJoPWIguNTfbyfIgBhLqXzcGzbqISpi5op9ewboeXNw0zSLSYbNOcDlahFz00d54tsffg"  # used in Angular



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]
